### ISSUE TITLE
Error in Debuge & relase Mode

### ISSUE THREAD

**Issue by OmidEbrahimii** [EVLF/Cypher-Rat-Source-Code#62]
Hello
if i run it with debug mode 
show me this error : 

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'AngelAndroid_v2.sockets.Data' threw an exception.
  Source=CypherRat
  StackTrace:
   at AngelAndroid_v2.CypherRat..ctor() in C:\Users\White Walker\Desktop\Cypher-Rat-Source-Code-main\AngelAndroid\Froms\CypherRat.vb:line 52

Inner Exception 1:
DirectoryNotFoundException: Could not find a part of the path 'C:\Users\%USERNAME%\Desktop\Cypher-Rat-Source-Code-main\AngelAndroid\bin\Debug\res\Config\Pass.inf'.

![image](https://user-images.githubusercontent.com/25227068/193547551-d5f36056-31ea-44bc-8964-5f0e49ffd060.png)

Output : 

Unhandled Exception: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: The type initializer for 'AngelAndroid_v2.sockets.Data' threw an exception. ---> System.TypeInitializationException: The type initializer for 'AngelAndroid_v2.sockets.Data' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\%USERNAME%\Desktop\Cypher-Rat-Source-Code-main\AngelAndroid\bin\Debug\res\Config\Pass.inf'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at AngelAndroid_v2.sockets.Data..cctor() in C:\Users\%USERNAME%\Desktop\Cypher-Rat-Source-Code-main\AngelAndroid\Sockets\Data.vb:line 57
   --- End of inner exception stack trace ---
   at AngelAndroid_v2.CypherRat..ctor() in C:\Users\%USERNAME%\Desktop\Cypher-Rat-Source-Code-main\AngelAndroid\Froms\CypherRat.vb:line 52
   --- End of inner exception stack trace ---
   at AngelAndroid_v2.My.MyProject.MyForms.Create__Instance__[T](T Instance) in :line 190
   at AngelAndroid_v2.My.MyProject.MyForms.get_CypherRat()
   at AngelAndroid_v2.My.MyApplication.OnCreateMainForm() in C:\Users\%USERNAME%\Desktop\Cypher-Rat-Source-Code-main\AngelAndroid\My Project\Application.Designer.vb:line 15
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at AngelAndroid_v2.My.MyApplication.Main(String[] Args) in :line 81
The program '[10824] CypherRat.exe' has exited with code 0 (0x0).
The program '[10824] CypherRat.exe: Program Trace' has exited with code 0 (0x0).

tell me how to fix it

and if i run it on relase mode : 

More ERROR : 
![image](https://user-images.githubusercontent.com/25227068/193547706-f1c01bb0-3619-4b5a-82cf-e06a21cb7f76.png)

Thanks

**Comment by EVLF** [comment]
![image](https://user-images.githubusercontent.com/54191699/195984119-51e3abe2-4019-46e8-bcbd-9a87cd4551a4.png)


and also  copy , .dll file
